-- emp_portal: RESTful API 表 (HSQLDB)
-- 存储 RESTful 接口定义和目录

CREATE TABLE EWA_RESTFUL (
 RS_UID VARCHAR(36) NOT NULL,
 CAT_UID VARCHAR(36) NOT NULL,
 RS_METHOD VARCHAR(10) NOT NULL,
 RS_NAME VARCHAR(200) NOT NULL,
 RS_NAME_EN VARCHAR(200) NOT NULL,
 RS_XMLNAME VARCHAR(200) NOT NULL,
 RS_ITEMNAME VARCHAR(100) NOT NULL,
 RS_PARAMETERS VARCHAR(1000) NOT NULL,
 RS_MEMO VARCHAR(16777216) DEFAULT NULL,
 RS_MEMO_EN VARCHAR(16777216) DEFAULT NULL,
 RS_STATUS VARCHAR(20) DEFAULT NULL,
 RS_CTIME TIMESTAMP DEFAULT NULL,
 RS_MTIME TIMESTAMP DEFAULT NULL,
 CONSTRAINT PK_EWA_RESTFUL PRIMARY KEY (RS_UID)
);
CREATE UNIQUE INDEX UN_EWA_RESTFUL ON EWA_RESTFUL (CAT_UID, RS_METHOD);

CREATE TABLE EWA_RESTFUL_CATALOG (
 CAT_UID VARCHAR(36) NOT NULL,
 CAT_PUID VARCHAR(36) NOT NULL,
 CAT_PATH VARCHAR(200) NOT NULL,
 CAT_PATH_FULL VARCHAR(1000) DEFAULT NULL,
 CAT_NAME VARCHAR(50) NOT NULL,
 CAT_NAME_EN VARCHAR(100) DEFAULT NULL,
 CAT_MEMO VARCHAR(16777216) DEFAULT NULL,
 CAT_MEMO_EN VARCHAR(16777216) DEFAULT NULL,
 CAT_LVL INTEGER NOT NULL,
 CAT_ORD INTEGER NOT NULL,
 CAT_STATUS VARCHAR(20) DEFAULT NULL,
 CAT_CTIME TIMESTAMP DEFAULT NULL,
 CAT_MTIME TIMESTAMP DEFAULT NULL,
 P0 VARCHAR(150) DEFAULT NULL,
 P1 VARCHAR(150) DEFAULT NULL,
 P2 VARCHAR(150) DEFAULT NULL,
 P3 VARCHAR(150) DEFAULT NULL,
 P4 VARCHAR(150) DEFAULT NULL,
 P5 VARCHAR(150) DEFAULT NULL,
 P6 VARCHAR(150) DEFAULT NULL,
 P7 VARCHAR(150) DEFAULT NULL,
 P8 VARCHAR(150) DEFAULT NULL,
 P9 VARCHAR(150) DEFAULT NULL,
 CONSTRAINT PK_EWA_RESTFUL_CATALOG PRIMARY KEY (CAT_UID)
);
CREATE INDEX IDX_EWA_RESTFUL_CATALOG ON EWA_RESTFUL_CATALOG (CAT_STATUS, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
CREATE INDEX IDX_EWA_RESTFUL_CATALOG_CAT_PUID ON EWA_RESTFUL_CATALOG (CAT_PUID);
CREATE INDEX IDX_EWA_RESTFUL_CATALOG_P0 ON EWA_RESTFUL_CATALOG (P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
