package com.gdxsoft.emp.demo;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 合并 emp_main_data 到 emp_portal
 */
public class MergeDatabases {
    private static final Logger LOGGER = LoggerFactory.getLogger(MergeDatabases.class);

    public static void main(String[] args) throws Exception {
        String hsqldbPort = System.getProperty("hsqldb.port", "11002");
        
        LOGGER.info("=== 合并 emp_main_data → emp_portal ===");

        // 启动 HSQLDB Server
        String[] databases = {"emp_portal", "emp_main_data"};
        HsqldbServerManager hsqldb = new HsqldbServerManager(Integer.parseInt(hsqldbPort), "hsqldb", databases);
        hsqldb.start();

        try {
            String sourceUrl = "jdbc:hsqldb:hsql://localhost:" + hsqldbPort + "/emp_main_data";
            String targetUrl = "jdbc:hsqldb:hsql://localhost:" + hsqldbPort + "/emp_portal";

            try (Connection sourceConn = DriverManager.getConnection(sourceUrl, "sa", "");
                 Connection targetConn = DriverManager.getConnection(targetUrl, "sa", "")) {

                // 获取 emp_main_data 中所有表
                List<String> tables = getTables(sourceConn);
                LOGGER.info("emp_main_data 共 {} 张表", tables.size());

                for (String table : tables) {
                    mergeTable(sourceConn, targetConn, table);
                }

                // SHUTDOWN COMPACT 确保写入
                try (Statement st = targetConn.createStatement()) {
                    st.execute("SHUTDOWN COMPACT");
                }
                LOGGER.info("emp_portal 已 SHUTDOWN COMPACT");

            }
        } finally {
            hsqldb.stop();
        }

        LOGGER.info("=== 合并完成 ===");
    }

    private static List<String> getTables(Connection conn) throws Exception {
        List<String> tables = new ArrayList<>();
        try (ResultSet rs = conn.getMetaData().getTables(null, "PUBLIC", "%", new String[]{"TABLE"})) {
            while (rs.next()) {
                tables.add(rs.getString("TABLE_NAME"));
            }
        }
        return tables;
    }

    private static void mergeTable(Connection sourceConn, Connection targetConn, String tableName) throws Exception {
        // 检查目标表是否已存在
        try (ResultSet rs = targetConn.getMetaData().getTables(null, "PUBLIC", tableName, new String[]{"TABLE"})) {
            if (rs.next()) {
                LOGGER.info("  表 {} 已存在，跳过", tableName);
                return;
            }
        }

        // 获取表结构并创建
        String probeSql = "SELECT * FROM \"" + tableName + "\" WHERE 1=0";
        ResultSetMetaData meta;
        try (Statement st = sourceConn.createStatement();
             ResultSet rs = st.executeQuery(probeSql)) {
            meta = rs.getMetaData();
        }

        int colCount = meta.getColumnCount();
        StringBuilder createSql = new StringBuilder("CREATE TABLE \"" + tableName + "\" (");

        for (int i = 1; i <= colCount; i++) {
            if (i > 1) createSql.append(", ");
            String colName = meta.getColumnName(i);
            int sqlType = meta.getColumnType(i);
            int precision = meta.getPrecision(i);
            int scale = meta.getScale(i);
            boolean autoIncrement = meta.isAutoIncrement(i);
            boolean nullable = meta.isNullable(i) == ResultSetMetaData.columnNullable;

            createSql.append("\"").append(colName).append("\" ");
            createSql.append(mapType(sqlType, precision, scale, autoIncrement));

            if (autoIncrement) {
                createSql.append(" GENERATED BY DEFAULT AS IDENTITY");
            }
            if (!nullable && !autoIncrement) {
                createSql.append(" NOT NULL");
            }
        }
        createSql.append(")");

        try (Statement st = targetConn.createStatement()) {
            st.execute(createSql.toString());
            LOGGER.info("  创建表 {}", tableName);
        }

        // 复制数据
        String selectSql = "SELECT * FROM \"" + tableName + "\"";
        String insertSql = "INSERT INTO \"" + tableName + "\" VALUES (" + String.join(",", java.util.Collections.nCopies(colCount, "?")) + ")";

        try (Statement st = sourceConn.createStatement();
             ResultSet rs = st.executeQuery(selectSql);
             PreparedStatement ps = targetConn.prepareStatement(insertSql)) {

            int count = 0;
            int batch = 0;
            while (rs.next()) {
                for (int i = 1; i <= colCount; i++) {
                    int sqlType = meta.getColumnType(i);
                    boolean autoIncrement = meta.isAutoIncrement(i);

                    if (autoIncrement) {
                        ps.setNull(i, Types.NULL);
                    } else {
                        ps.setObject(i, rs.getObject(i), sqlType);
                    }
                }
                ps.addBatch();
                count++;
                batch++;

                if (batch >= 1000) {
                    ps.executeBatch();
                    batch = 0;
                }
            }
            if (batch > 0) {
                ps.executeBatch();
            }
            targetConn.commit();
            LOGGER.info("  复制 {} 行到 {}", count, tableName);
        }
    }

    private static String mapType(int sqlType, int precision, int scale, boolean autoIncrement) {
        if (autoIncrement) {
            return "BIGINT";
        }
        switch (sqlType) {
            case Types.BIT:
            case Types.BOOLEAN:
                return "BOOLEAN";
            case Types.TINYINT:
                return "TINYINT";
            case Types.SMALLINT:
                return "SMALLINT";
            case Types.INTEGER:
                return "INTEGER";
            case Types.BIGINT:
                return "BIGINT";
            case Types.REAL:
            case Types.FLOAT:
                return "REAL";
            case Types.DOUBLE:
                return "DOUBLE";
            case Types.NUMERIC:
            case Types.DECIMAL:
                if (scale > 0) {
                    return "DECIMAL(" + precision + "," + scale + ")";
                }
                return "DECIMAL(" + precision + ")";
            case Types.CHAR:
                return "CHAR(" + Math.max(1, precision) + ")";
            case Types.VARCHAR:
            case Types.LONGVARCHAR:
            case Types.NCHAR:
            case Types.NVARCHAR:
            case Types.LONGNVARCHAR:
                if (precision > 100000 || precision <= 0) {
                    return "CLOB";
                }
                return "VARCHAR(" + precision + ")";
            case Types.DATE:
                return "DATE";
            case Types.TIME:
                return "TIME";
            case Types.TIMESTAMP:
                return "TIMESTAMP";
            case Types.BINARY:
            case Types.VARBINARY:
            case Types.LONGVARBINARY:
            case Types.BLOB:
                return "BLOB";
            case Types.CLOB:
            case Types.NCLOB:
                return "CLOB";
            default:
                return "VARCHAR(1000)";
        }
    }
}
