// 项目默认内容
EWAC_DEF = {};

// 列表所需映射
EWAC_DEF.LIST = {
	ADM_ID : {
		SQL : "'SELECT ADM_ID,ADM_NAME FROM ADM_USER WHERE SUP_ID=@G_SUP_ID ORDER BY ADM_NAME'",
		TEXT : "'ADM_NAME'",
		VALUE : "'ADM_ID'"
	},
	SUP_ID : {
		SQL : "'SELECT SUP_ID,SUP_NAME FROM SUP_MAIN WHERE 1=1 ORDER BY SUP_NAME'",
		TEXT : "'SUP_NAME'",
		VALUE : "'SUP_ID'"
	},
	BAS_TAG : {
		SQL : "'SELECT BAS_TAG,BAS_TAG_NAME FROM BAS_TAG_NAME WHERE BAS_TAG_GRP='' ORDER BY BAS_TAG_GRP'",
		TEXT : "'SUP_NAME'",
		VALUE : "'SUP_ID'"
	}
};

// 生成SQL语句所需的映射
EWAC_DEF.FIELD_MAP = {
	ADM_ID : "G_ADM_ID",
	SUP_ID : "G_SUP_ID",
	OWN_SUP_ID : "G_SUP_ID",
	ADM_UNID : "G_ADM_UNID",
	SUP_UNID : "G_SUP_UNID"

};
// where 条件的默认
EWAC_DEF.WHERE = {
	SUP_ID : "G_SUP_ID",
	OWN_SUP_ID : "G_SUP_ID",
	SUP_UNID : "G_SUP_UNID"
};