
CREATE TABLE CRM_COM (
	CRM_COM_ID int IDENTITY(1,1) NOT NULL,
	SUP_ID int NOT NULL,
	CRM_COM_NAME nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL,
	CRM_COM_SNAME nvarchar(150) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_CODE varchar(40) COLLATE Chinese_PRC_CI_AS NULL,
	ARE_ID int NULL,
	CRM_COM_ARE_DES nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_ADDR nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_ZIP varchar(10) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_EMAIL nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_TELE nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_MOBILE varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_SIZE_TAG varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_TYPE_TAG varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_CAL_TAG varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CHINA_CAMP nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_CDATE datetime NULL,
	CRM_COM_MDATE datetime NULL,
	CRM_COM_STATE varchar(10) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_SALE varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_NOTE ntext COLLATE Chinese_PRC_CI_AS NULL,
	ADM_ID int NULL,
	USE_STATE nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT 'USED' NULL,
	SER_TAG1 varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CITY_ID1 int NULL,
	CRM_COM_SCORE money NULL,
	CRM_COM_SCORE_FID int NULL,
	CEM_COM_HTTP varchar(2000) COLLATE Chinese_PRC_CI_AS NULL,
	RECRUIT_STATUS varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	SIT_ID int NULL,
	CRM_COM_UNID char(36) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_DISCOUNT money NULL,
	CRM_PIP_STATUS char(36) COLLATE Chinese_PRC_CI_AS NULL,
	BUSINESS_NUMBER varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_CLASS varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_CREDIT_LIMIT money NULL,
	CRM_COM_FAX varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_LAT numeric(30,26) NULL,
	CRM_COM_LNG numeric(30,26) NULL,
	M_ADM_ID int NULL,
	AUS_PAYDAYS nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_MARGIN float NULL,
	AUS_PASSWORD nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_DRIVINGLICENCE nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_TAID int NULL,
	AUS_COUNTRY nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_STATEORPROVINCE nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_CREDITLIMIT money NULL,
	AUS_PAYMENTCONDITION nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_TYPE nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_INITIAL nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_CLASSID int NULL,
	AUS_OVERSEA bit NULL,
	AUS_REPORTING bit NULL,
	AUS_CONTACT nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	AUS_MARKUP money NULL,
	IS_AUS int NULL,
	AUS_DIS float NULL,
	PROVINCE_ID int NULL,
	GYAP_CODE_NUM int NULL,
	CRM_COM_GROUP varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_NAME_EN nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_COUNTRY_ID int NULL,
	CRM_COM_COOP_STATUS varchar(30) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_BUSINESS_TYPE varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_INDUSTRY_CAT varchar(200) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_INDUSTRY_SUBCAT varchar(1000) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_COM_STAR_STATUS varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	DISTRICT_ID int NULL,
	CRM_COM_INDUSTRY_OTHER nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK_CRM_COM PRIMARY KEY (CRM_COM_ID)
);
 CREATE NONCLUSTERED INDEX IDX_CRM_COM1 ON demo.dbo.CRM_COM (  SUP_ID ASC  , USE_STATE ASC  )  
	 INCLUDE ( ADM_ID , CRM_COM_ID , CRM_PIP_STATUS ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_CRM_COM_1 ON demo.dbo.CRM_COM (  CRM_COM_CDATE ASC  )  
	 INCLUDE ( ADM_ID ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_CRM_COM_SUPID_USESTATE_SCORE ON demo.dbo.CRM_COM (  SUP_ID ASC  , USE_STATE ASC  , CRM_COM_SCORE ASC  )  
	 INCLUDE ( ADM_ID , ARE_ID , CRM_COM_CAL_TAG , CRM_COM_CDATE , CRM_COM_ID , CRM_COM_MDATE , CRM_COM_NAME , CRM_COM_SALE , CRM_COM_SIZE_TAG , CRM_COM_STATE , CRM_COM_TYPE_TAG ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_CRM_COM_SUPID_USESTATE_SCORE_A ON demo.dbo.CRM_COM (  SUP_ID ASC  , USE_STATE ASC  , CRM_COM_SCORE DESC  )  
	 INCLUDE ( ADM_ID , CRM_COM_ID ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX idx_crm_com_sup_id ON demo.dbo.CRM_COM (  SUP_ID ASC  , CRM_COM_SCORE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

-- Extended properties

EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'郜霄', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'供应商编号', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'SUP_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'梁先榕', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_NAME';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'施翠', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_SNAME';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'晁保星', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_CODE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'区域编号', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'ARE_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'区域描述', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_ARE_DES';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'平裕', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_ADDR';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'汪松雄', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_ZIP';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'弘岚', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_EMAIL';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'谢姣艳', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_TELE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'印荣', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_MOBILE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'荣生', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_SIZE_TAG';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'徐婵', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_TYPE_TAG';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'管朋', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_CAL_TAG';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'寿利', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_CDATE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'劳燕莎', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_MDATE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'支黛', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_STATE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'巢世宁', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_SALE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'孔纯', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_NOTE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'计义', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'ADM_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'客户分组管理，例如留学', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_GROUP';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'供应商合作状态', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_COM', @level2type=N'Column', @level2name=N'CRM_COM_COOP_STATUS';



CREATE TABLE CRM_CUS (
	CRM_CUS_ID int IDENTITY(1,1) NOT NULL,
	CRM_COM_ID int NOT NULL,
	SUP_ID int NOT NULL,
	CRM_CUS_TYPE varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_NAME nvarchar(140) COLLATE Chinese_PRC_CI_AS NOT NULL,
	CRM_CUS_TITLE nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_SEX varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_EMAIL nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_TELE nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_MOBILE varchar(100) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_ADDR nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_JOB nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_HOBBY nvarchar(800) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_CDATE datetime NULL,
	CRM_CUS_MDATE datetime NULL,
	CRM_CUS_LDATE datetime NULL,
	CRM_CUS_CNUM int NULL,
	CRM_CUS_NOTE nvarchar(800) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_TAG varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_MASTER varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	ADM_ID int NULL,
	CRM_CUS_QQ nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_MSN nvarchar(80) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_STATUS varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	DRIVING_LINENCE varchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_FROM_ADM_ID int NULL,
	CRM_CUS_UNID char(36) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_LVL varchar(200) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK_CRM_CUST PRIMARY KEY (CRM_CUS_ID)
);
 CREATE NONCLUSTERED INDEX IDX_CRM_CUS_1 ON demo.dbo.CRM_CUS (  CRM_CUS_MASTER ASC  )  
	 INCLUDE ( CRM_COM_ID , CRM_CUS_ID ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_CRM_CUS_2 ON demo.dbo.CRM_CUS (  CRM_COM_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

-- Extended properties

EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'冀莺娣', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'段霞', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_COM_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'供应商编号', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'SUP_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'厍富志', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_NAME';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'容民', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_TITLE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'慎瑞', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_SEX';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'焦莲', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_EMAIL';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'温滢', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_TELE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'居蓉', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_MOBILE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'林有', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_ADDR';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'计春馥', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_JOB';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'越芬', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_HOBBY';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'关士敬', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_CDATE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'劳学天', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_MDATE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最后联系日期', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_LDATE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'暴彬', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_CNUM';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'嵇海', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_NOTE';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'雷昭', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_TAG';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'仰勇友', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'CRM_CUS_MASTER';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'孟磊', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_CUS', @level2type=N'Column', @level2name=N'ADM_ID';



CREATE TABLE CRM_RECORD (
	CRM_RECORD_ID int IDENTITY(1,1) NOT NULL,
	CRM_RECORD_WAY varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_RECORD_CONTENT nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_CUS_ID int NOT NULL,
	ADM_ID int NOT NULL,
	SUP_ID int NOT NULL,
	CRM_RECORD_TIME datetime NULL,
	CRM_RECORD_OB1 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_RECORD_OB2 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	CRM_RECORD_OB3 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL,
	NEXT_TIME datetime NULL,
	CRM_RECORD_STATUS varchar(20) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK_CRM_RECORD PRIMARY KEY (CRM_RECORD_ID)
);
 CREATE NONCLUSTERED INDEX IDX_CRM_RECORD_SUP_ID ON demo.dbo.CRM_RECORD (  SUP_ID ASC  )  
	 INCLUDE ( CRM_CUS_ID , CRM_RECORD_TIME ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

-- Extended properties

EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'联系记录编号', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'汪朗', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_WAY';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'董莲', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_CONTENT';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'联系人编号', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_CUS_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'用户id', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'ADM_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'供应商id', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'SUP_ID';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建记录时间', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_TIME';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'祁海', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_OB1';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'桂岩', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_OB2';
EXEC demo.sys.sp_addextendedproperty @name=N'MS_Description', @value=N'赖若之', @level0type=N'Schema', @level0name=N'dbo', @level1type=N'Table', @level1name=N'CRM_RECORD', @level2type=N'Column', @level2name=N'CRM_RECORD_OB3';


INSERT INTO crm_com (SUP_ID,CRM_COM_NAME,CRM_COM_SNAME,CRM_COM_CODE,ARE_ID,CRM_COM_ARE_DES,CRM_COM_ADDR,CRM_COM_ZIP,CRM_COM_EMAIL,CRM_COM_TELE,CRM_COM_MOBILE,CRM_COM_SIZE_TAG,CRM_COM_TYPE_TAG,CRM_COM_CAL_TAG,CRM_CHINA_CAMP,CRM_COM_CDATE,CRM_COM_MDATE,CRM_COM_STATE,CRM_COM_SALE,CRM_COM_NOTE,ADM_ID,USE_STATE,SER_TAG1,CITY_ID1,CRM_COM_SCORE,CRM_COM_SCORE_FID,CEM_COM_HTTP,RECRUIT_STATUS,SIT_ID,CRM_COM_UNID,CRM_COM_DISCOUNT,CRM_PIP_STATUS,BUSINESS_NUMBER,CRM_COM_CLASS,CRM_COM_CREDIT_LIMIT,CRM_COM_FAX,CRM_COM_LAT,CRM_COM_LNG,M_ADM_ID,AUS_PAYDAYS,AUS_MARGIN,AUS_PASSWORD,AUS_DRIVINGLICENCE,AUS_TAID,AUS_COUNTRY,AUS_STATEORPROVINCE,AUS_CREDITLIMIT,AUS_PAYMENTCONDITION,AUS_TYPE,AUS_INITIAL,AUS_CLASSID,AUS_OVERSEA,AUS_REPORTING,AUS_CONTACT,AUS_MARKUP,IS_AUS,AUS_DIS,PROVINCE_ID,GYAP_CODE_NUM,CRM_COM_GROUP,CRM_COM_NAME_EN,CRM_COM_COUNTRY_ID,CRM_COM_COOP_STATUS,CRM_COM_BUSINESS_TYPE,CRM_COM_INDUSTRY_CAT,CRM_COM_INDUSTRY_SUBCAT,CRM_COM_STAR_STATUS,DISTRICT_ID,CRM_COM_INDUSTRY_OTHER) VALUES
	 (3,N'Ming International Travel INC.Services',NULL,NULL,502005,N'',N'5214.N.Rosemead Blvd San Gabriel, CA  ',N'91776',N'',N'010-44355234',N'',N'CRM_COM_SIZE_2',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_OK',N'',20,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'128eb904-ce3e-468b-bb73-3c21e886df1c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'连怡姬',NULL,NULL,110000,N'',N'北京市朝阳区三元桥远洋新干线',N'100000',N'',N'12110230295',N'12157645095',N'CRM_COM_SIZE_2',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_OK',N'主要做美国北欧的旅游',375,N'USED',NULL,NULL,4.1786,1118,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'北京易为畅游航空服务有限公司',NULL,NULL,110000,N'',N'',N'',N'',N'',N'12170099670',N'CRM_COM_SIZE_2',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_OK',N'',827,N'USED',NULL,291,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'128eb904-ce3e-468b-bb73-3c21e886df1c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'大连创感文化传播有限公司-不需要',NULL,NULL,210200,N'',N'大连市中山区五五路30号名仕国际B606室',N'116000',N'',N'',N'12158782426',N'CRM_COM_SIZE_2',N'CRM_R_S',N'CRM_IND_T',NULL,'2014-01-10 09:51:14.293','2014-01-10 09:51:14.280',N'CRM_S_OK',N'CRM_SALE_NEW',N'',594,N'USED',NULL,NULL,NULL,NULL,N'http://',N'',NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'格致旅行网',N'',NULL,NULL,NULL,N'',N'',N'lf28@189.cn',N'1391040933331',N'1391040933331',N'CRM_COM_SIZE_1',N'CRM_R_C',N'CRM_IND_T',NULL,NULL,'2017-12-22 17:41:28.420',N'CRM_S_OK',N'CRM_SALE_NEW',N'',19,N'USED',N'',0,NULL,NULL,N'',NULL,NULL,NULL,NULL,N'128eb904-ce3e-468b-bb73-3c21e886df1c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'北京世纪和平国际文化教育交流中心',NULL,NULL,110102,N'奔福',东欧网络总公司,N'100044',N'e2bs72@renren.com',N'010-44348991',N'12130890244',N'CRM_COM_SIZE_3',N'CRM_R_S',N'CRM_IND_N',NULL,'2012-12-31 12:06:48.867',NULL,N'CRM_S_OK',N'CRM_SALE_DEAL',N'',32,N'USED',NULL,NULL,3.5714,1457,N'http://www.bjcpce.com/',NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_20',NULL,NULL,NULL,NULL),
	 (3,N'天津外国语学院',NULL,NULL,120000,N'',N'天津市马场道117号',N'',N'user4153@teachers.edu.cn',N'010-44211592',N'12138216360',N'CRM_COM_SIZE_4',N'CRM_R_S',N'CRM_IND_E3',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_OK',N'',33,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'74b16c7b-0978-4576-8ec6-0bda9370fb23',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'Australia Tours Company',NULL,NULL,601,N'',N'Level 2, 171 La Trobe Street,  Melbourne VIC3000 Australia ',N'',N'96b78y15904@mail.edu.cn',N'+61 3 9639 8097',N'+61 3 9639 8097',N'CRM_COM_SIZE_1',N'CRM_R_C',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',20,N'USED',NULL,292,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'128eb904-ce3e-468b-bb73-3c21e886df1c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'HOMESTAY AUSTRALIA P/L',NULL,NULL,601,N'',N'1/95 Fullers Rd, Chatswood NSW 澳大利亚',N'',N'user5336@139.com',N'0061 400 468 658',N'0061 400 468 658',N'CRM_COM_SIZE_1',N'CRM_R_S',N'CRM_IND_P',NULL,NULL,'2015-01-16 11:59:24.417',N'CRM_S_OK',N'CRM_SALE_OK',N'',20,N'USED',N'SER_TAG_CAMP',292,NULL,NULL,N'',NULL,NULL,NULL,NULL,N'128eb904-ce3e-468b-bb73-3c21e886df1c',N'',NULL,NULL,N'',NULL,NULL,662,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14,NULL,NULL,N'CC_IND_CAT_13',NULL,NULL,NULL,NULL),
	 (3,N'test2',NULL,NULL,110000,N'北京市',N'',N'',N'',N'',N'',N'CRM_COM_SIZE_1',N'CRM_R_C',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',19,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'd3bea855-cc2e-47aa-b255-72e8fcc484b4',NULL,N'128eb904-ce3e-468b-bb73-3c21e886df1c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL);
INSERT INTO crm_com (SUP_ID,CRM_COM_NAME,CRM_COM_SNAME,CRM_COM_CODE,ARE_ID,CRM_COM_ARE_DES,CRM_COM_ADDR,CRM_COM_ZIP,CRM_COM_EMAIL,CRM_COM_TELE,CRM_COM_MOBILE,CRM_COM_SIZE_TAG,CRM_COM_TYPE_TAG,CRM_COM_CAL_TAG,CRM_CHINA_CAMP,CRM_COM_CDATE,CRM_COM_MDATE,CRM_COM_STATE,CRM_COM_SALE,CRM_COM_NOTE,ADM_ID,USE_STATE,SER_TAG1,CITY_ID1,CRM_COM_SCORE,CRM_COM_SCORE_FID,CEM_COM_HTTP,RECRUIT_STATUS,SIT_ID,CRM_COM_UNID,CRM_COM_DISCOUNT,CRM_PIP_STATUS,BUSINESS_NUMBER,CRM_COM_CLASS,CRM_COM_CREDIT_LIMIT,CRM_COM_FAX,CRM_COM_LAT,CRM_COM_LNG,M_ADM_ID,AUS_PAYDAYS,AUS_MARGIN,AUS_PASSWORD,AUS_DRIVINGLICENCE,AUS_TAID,AUS_COUNTRY,AUS_STATEORPROVINCE,AUS_CREDITLIMIT,AUS_PAYMENTCONDITION,AUS_TYPE,AUS_INITIAL,AUS_CLASSID,AUS_OVERSEA,AUS_REPORTING,AUS_CONTACT,AUS_MARKUP,IS_AUS,AUS_DIS,PROVINCE_ID,GYAP_CODE_NUM,CRM_COM_GROUP,CRM_COM_NAME_EN,CRM_COM_COUNTRY_ID,CRM_COM_COOP_STATUS,CRM_COM_BUSINESS_TYPE,CRM_COM_INDUSTRY_CAT,CRM_COM_INDUSTRY_SUBCAT,CRM_COM_STAR_STATUS,DISTRICT_ID,CRM_COM_INDUSTRY_OTHER) VALUES
	 (3,中国公募数码代表处,NULL,NULL,110000,N'北京市',N'西城区育教胡同33号',N'',N'',N'010-44176838',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_N',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',827,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_20',NULL,NULL,NULL,NULL),
	 (3,东亚食品社,NULL,NULL,110000,N'北京市',N'北京市东城区夕照寺中街19号',N'',N'',N'010-44813848',N'',N'CRM_COM_SIZE_4',N'CRM_R_C',N'CRM_IND_N',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',827,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_20',NULL,NULL,NULL,NULL),
	 (3,上海煤炭控股公司,NULL,NULL,110000,N'北京市',N'石佛营西里2号',N'',N'',N'010-44476114',N'',N'CRM_COM_SIZE_5',N'CRM_R_C',N'CRM_IND_N',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',827,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_20',NULL,NULL,NULL,NULL),
	 (3,昆仑系统总公司,NULL,NULL,110000,N'北京市',N'海淀区西四环北路11号',N'',N'',N'010-44987542',N'',N'CRM_COM_SIZE_5',N'CRM_R_C',N'CRM_IND_N',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',827,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_20',NULL,NULL,NULL,NULL),
	 (3,N'中国国际旅行社总社(蓝堡店)',NULL,NULL,110000,N'北京市',N'北京市朝阳区东三环。大望路3号(大望路地铁A口北50米)。蓝堡国际中心2座商业街S219 ',N'',N'user7658@foxmail.com',N'010-44500847',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'发送紧急计划
',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'北京太美国际旅行社有限公司',NULL,NULL,110000,N'北京市',N'日坛北路19号15层1507 ',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'发送紧急计划
',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'海洋国际旅行社有限责任公司',NULL,NULL,110000,N'北京市',N'北三环西路甲18号',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'北京友协国际旅行社有限公司',NULL,NULL,110000,N'北京市',N'北京东城区南河沿大街97号 ',N'',N'user56745651@gmail.com',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'发送紧急计划
',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'北京中国国际旅行社有限公司',NULL,NULL,110000,N'北京市',N'北京市东直门南大街9号华普花园B座1504',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'天马国际旅行社',NULL,NULL,110000,N'北京市',N'东四十条21号',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'发送紧急计划
',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL);
INSERT INTO crm_com (SUP_ID,CRM_COM_NAME,CRM_COM_SNAME,CRM_COM_CODE,ARE_ID,CRM_COM_ARE_DES,CRM_COM_ADDR,CRM_COM_ZIP,CRM_COM_EMAIL,CRM_COM_TELE,CRM_COM_MOBILE,CRM_COM_SIZE_TAG,CRM_COM_TYPE_TAG,CRM_COM_CAL_TAG,CRM_CHINA_CAMP,CRM_COM_CDATE,CRM_COM_MDATE,CRM_COM_STATE,CRM_COM_SALE,CRM_COM_NOTE,ADM_ID,USE_STATE,SER_TAG1,CITY_ID1,CRM_COM_SCORE,CRM_COM_SCORE_FID,CEM_COM_HTTP,RECRUIT_STATUS,SIT_ID,CRM_COM_UNID,CRM_COM_DISCOUNT,CRM_PIP_STATUS,BUSINESS_NUMBER,CRM_COM_CLASS,CRM_COM_CREDIT_LIMIT,CRM_COM_FAX,CRM_COM_LAT,CRM_COM_LNG,M_ADM_ID,AUS_PAYDAYS,AUS_MARGIN,AUS_PASSWORD,AUS_DRIVINGLICENCE,AUS_TAID,AUS_COUNTRY,AUS_STATEORPROVINCE,AUS_CREDITLIMIT,AUS_PAYMENTCONDITION,AUS_TYPE,AUS_INITIAL,AUS_CLASSID,AUS_OVERSEA,AUS_REPORTING,AUS_CONTACT,AUS_MARKUP,IS_AUS,AUS_DIS,PROVINCE_ID,GYAP_CODE_NUM,CRM_COM_GROUP,CRM_COM_NAME_EN,CRM_COM_COUNTRY_ID,CRM_COM_COOP_STATUS,CRM_COM_BUSINESS_TYPE,CRM_COM_INDUSTRY_CAT,CRM_COM_INDUSTRY_SUBCAT,CRM_COM_STAR_STATUS,DISTRICT_ID,CRM_COM_INDUSTRY_OTHER) VALUES
	 (3,N'中城国际旅行社',NULL,NULL,110000,N'北京市',N'东城区安定门外大街甲88号中联大厦702室',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'罗欣',NULL,NULL,110000,N'北京市',N'北京市通州区玉桥中路甲4号聚仙居宾馆一层',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_S',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL),
	 (3,N'正安国际旅行社有限责任公司',NULL,NULL,110000,N'北京市',N'',N'',N'',N'',N'',N'CRM_COM_SIZE_5',N'CRM_R_C',N'CRM_IND_T',NULL,NULL,NULL,N'CRM_S_OK',N'CRM_SALE_NEW',N'主要是做老年团',129,N'USED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'214f6355-54e8-444a-829f-835103e112fb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'CC_IND_CAT_16',NULL,NULL,NULL,NULL);


INSERT INTO [CRM_CUS] (CRM_COM_ID,SUP_ID,CRM_CUS_TYPE,CRM_CUS_NAME,CRM_CUS_TITLE,CRM_CUS_SEX,CRM_CUS_EMAIL,CRM_CUS_TELE,CRM_CUS_MOBILE,CRM_CUS_ADDR,CRM_CUS_JOB,CRM_CUS_HOBBY,CRM_CUS_CDATE,CRM_CUS_MDATE,CRM_CUS_LDATE,CRM_CUS_CNUM,CRM_CUS_NOTE,CRM_CUS_TAG,CRM_CUS_MASTER,ADM_ID,CRM_CUS_QQ,CRM_CUS_MSN,CRM_CUS_STATUS,DRIVING_LINENCE,CRM_CUS_FROM_ADM_ID,CRM_CUS_UNID,CRM_CUS_LVL) VALUES
	 (200014,3,NULL,华山电力所,黄山电信管理有限责任公司,N'F',N'',N'010-44215554',N'',N'',N'',N'','2011-11-30 14:55:40.007','2011-11-30 16:11:03.693',NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200015,3,NULL,N'.',华夏文化家政股份有限公司,N'F',N'',N'010-44193689',N'',N'',N'',N'','2011-11-30 16:14:50.303',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200016,3,NULL,大西洋新材料办事处,祁连山小贷加工工作室,N'F',N'',N'010-44029512',N'',N'',N'',N'','2011-11-30 16:19:50.817',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200017,3,NULL,N'靳云',N'柳淑',N'F',N'',N'010-44715737',N'',N'',N'',N'','2011-11-30 16:22:43.277',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200018,3,NULL,N'宫磊',N'花丽锦',N'M',N'3y8v0xp1346@139.com',N'44701687',N'',N'',N'',N'','2011-11-30 16:29:46.693',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200019,3,NULL,N'杭腾诚',N'江婷瑶',N'M',N'tw2qp@alumni.com',N'010-58702277---85906788',N'',N'',N'',N'','2011-11-30 16:31:19.767',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200020,3,NULL,N'姜义',N'宓强',N'F',N'user2626423@yeah.net',N'',N'12179029403',N'',N'',N'金钱概念重，利益大于一切','2011-11-30 16:35:43.017',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200021,3,NULL,N'许会',N'费钧',N'M',N'04629w4e@yeah.net',N'44760494',N'',N'',N'',N'','2011-11-30 16:37:17.737',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200022,3,NULL,N'黎翠',N'甄宏诚',N'M',N'user8066@edu.cn',N'12153976343',N'',N'北京市东直门南大街9号华普花园B座1504',N'',N'','2011-11-30 16:40:22.947',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200023,3,NULL,N'郏娅菲',N'伍宁',N'M',N'华荷蓉7712@hotmail.com',N'44092015',N'12189992341',N'',N'',N'','2011-11-30 16:44:01.523',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL);
INSERT INTO [CRM_CUS] (CRM_COM_ID,SUP_ID,CRM_CUS_TYPE,CRM_CUS_NAME,CRM_CUS_TITLE,CRM_CUS_SEX,CRM_CUS_EMAIL,CRM_CUS_TELE,CRM_CUS_MOBILE,CRM_CUS_ADDR,CRM_CUS_JOB,CRM_CUS_HOBBY,CRM_CUS_CDATE,CRM_CUS_MDATE,CRM_CUS_LDATE,CRM_CUS_CNUM,CRM_CUS_NOTE,CRM_CUS_TAG,CRM_CUS_MASTER,ADM_ID,CRM_CUS_QQ,CRM_CUS_MSN,CRM_CUS_STATUS,DRIVING_LINENCE,CRM_CUS_FROM_ADM_ID,CRM_CUS_UNID,CRM_CUS_LVL) VALUES
	 (200025,3,NULL,N'蓟群',N'曾珠桂',N'M',N'3505g364@sina.com',N'44655796',N'',N'',N'',N'','2011-11-30 16:50:17.177',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200026,3,NULL,N'荀筠',N'路厚民',N'M',N'user4773@51.com',N'44998358',N'',N'',N'',N'','2011-11-30 16:51:03.137',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200027,3,NULL,N'糜聪育',N'夔琳',N'F',N'1l56@139.com',N'010-44312586',N'',N'',N'',N'','2011-11-30 16:55:31.13',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200028,3,NULL,N'经强',N'段慧',N'F',N'1755159064@qqcom',N'010-44521669',N'',N'',N'',N'','2011-11-30 16:59:34.0',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200029,3,NULL,N'郝泽',N'阎彪',N'M',N'112850l68074@139.com',N'44580394',N'',N'',N'',N'','2011-11-30 17:20:17.3',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200030,3,NULL,N'桓可',N'贾斌',N'F',N'4p6udbc3815@189.cn',N'44440014',N'',N'',N'',N'','2011-11-30 17:24:31.73','2011-11-30 17:34:59.637',NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200031,3,NULL,N'简英',N'桓元',N'M',N'user9275@mail.edu.cn',N'44280846',N'',N'',N'',N'','2011-11-30 17:26:51.61',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200032,3,NULL,N'钭龙',N'经清',N'F',N'l4r88i8894@kaixin001.com',N'010-44917295',N'',N'',N'',N'','2011-11-30 17:29:18.287',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200033,3,NULL,N'融瑾',N'昝致',N'M',N'cxrf3@hotmail.com',N'010-44441195',N'',N'',N'',N'','2011-11-30 17:30:52.523',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200034,3,NULL,N'邓星鹏',N'房士',N'M',N'user1467@alumni.com',N'010-44922581',N'',N'',N'',N'','2011-11-30 17:32:33.383','2011-12-01 11:54:55.53',NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',36,N'',N'',NULL,NULL,NULL,NULL,NULL);
INSERT INTO [CRM_CUS] (CRM_COM_ID,SUP_ID,CRM_CUS_TYPE,CRM_CUS_NAME,CRM_CUS_TITLE,CRM_CUS_SEX,CRM_CUS_EMAIL,CRM_CUS_TELE,CRM_CUS_MOBILE,CRM_CUS_ADDR,CRM_CUS_JOB,CRM_CUS_HOBBY,CRM_CUS_CDATE,CRM_CUS_MDATE,CRM_CUS_LDATE,CRM_CUS_CNUM,CRM_CUS_NOTE,CRM_CUS_TAG,CRM_CUS_MASTER,ADM_ID,CRM_CUS_QQ,CRM_CUS_MSN,CRM_CUS_STATUS,DRIVING_LINENCE,CRM_CUS_FROM_ADM_ID,CRM_CUS_UNID,CRM_CUS_LVL) VALUES
	 (200035,3,NULL,N'郭弘盛',N'',N'F',N'a3st@163.com',N'44389643',N'',N'',N'',N'','2011-11-30 17:57:04.953','2011-12-02 14:18:02.717',NULL,0,N'',N'CRM_CUS_NEW',N'COM_YES',38,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200035,3,NULL,N'茹龙',N'',N'M',N'',N'',N'',N'',N'',N'','2011-11-30 17:57:17.42',NULL,NULL,0,N'',N'',N'',38,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200036,3,NULL,N'敖秀',N'',N'F',N'',N'010-44440473 010-44793404 010-44062402',N'12195676292',N'西安市高新区科技路金鹰国际B座1408室',N'',N'','2011-11-30 18:03:46.013',NULL,NULL,0,N'',N'CRM_CUS_OK',N'COM_YES',67,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200037,3,NULL,N'云璐',N'姬荷',N'M',N'',N'010-44583616',N'12178722101',N'',N'',N'','2011-12-01 11:19:21.75',NULL,NULL,0,N'',N'CRM_CUS_OK',N'COM_YES',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200038,3,NULL,N'乌淑薇',N'晏环',N'M',N'',N'010-44670213',N'12138811559',N'',N'',N'','2011-12-01 11:22:21.627',NULL,NULL,0,N'',N'CRM_CUS_OK',N'COM_YES',67,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200038,3,NULL,N'束民康',N'',N'F',N'',N'010-44570673',N'12174911955',N'',N'',N'','2011-12-01 11:23:09.077',NULL,NULL,0,N'',N'CRM_CUS_OK',N'COM_NO',67,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200036,3,NULL,N'姬义',N'',N'M',N'',N'010-44795041',N'',N'',N'',N'','2011-12-01 11:25:54.89',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'COM_NO',67,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200039,3,NULL,N'山政永',N'',N'',N'',N'010-44115353-643',N'',N'',N'',N'','2011-12-01 11:29:40.093',NULL,NULL,0,N'',N'CRM_CUS_OK',N'COM_YES',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200040,3,NULL,N'徐融',东方中介代表处,N'M',N'2m419@eyou.com',N'',N'',N'',N'',N'','2011-12-01 11:40:13.733',NULL,NULL,0,N'',N'CRM_CUS_NEW',N'',827,N'',N'',NULL,NULL,NULL,NULL,NULL),
	 (200041,3,NULL,N'蓝竹艳',N'',N'F',N'',N'010-44314196',N'12184541584',N'',N'',N'','2011-12-01 11:42:35.61',NULL,NULL,0,N'',N'CRM_CUS_OK',N'COM_YES',827,N'',N'',NULL,NULL,NULL,NULL,NULL);


INSERT INTO CRM_RECORD (CRM_RECORD_WAY,CRM_RECORD_CONTENT,CRM_CUS_ID,ADM_ID,SUP_ID,CRM_RECORD_TIME,CRM_RECORD_OB1,CRM_RECORD_OB2,CRM_RECORD_OB3,NEXT_TIME,CRM_RECORD_STATUS) VALUES
	 (N'CRM_RECORD_WAY1',国际传媒分公司,200006,35,3,'2011-11-30 00:00:00.000',N'相梅',N'',N'',NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',黄河制药美发有限责任公司,200007,35,3,'2011-11-30 00:00:00.000',N'郝泰',N'',N'',NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',华夏酒店中介院,200008,35,3,'1900-01-01 00:00:00.000',N'双琛',N'',N'',NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',N'很多海淀区学校都有友好校，暑假寒假一般都去友好校交流！但是经学校同意，可以做游学！',200009,35,3,'1900-01-01 00:00:00.000',N'巩琛',N'',N'',NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',N'111',200662,19,3,'2012-03-05 16:15:26.427',N'1',NULL,NULL,'2012-03-13 16:15:00.000',N'USED'),
	 (N'CRM_RECORD_WAY5',N'通过QQ联系报价问题，由于同一个团报价第二次高于第一次，在qq上与Kendy达成一致，最终按第一次报价确认价格。',200661,456,3,'2013-11-07 17:48:08.410',N'供应商报价',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY3',N'新增澳洲团组行程报价，已通过邮件发送给Kendy，周一回复',200661,456,3,'2013-11-08 14:49:21.693',N'新增澳洲团组行程报价',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY5',N'通过qq联系向kendy发送团组名单并索要酒店信息及地接函',200661,456,3,'2013-11-12 12:04:01.867',N'提供酒店信息及地接函',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY5',N'通过qq联系，咨询对方有关澳洲公务信息',308219,456,3,'2013-11-19 16:34:00.003',N'咨询澳洲公务',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY5',N'通过qq跟kendy商量付款方式，最后确认可先付80%，另外20%可等回团后支付',200661,456,3,'2013-11-25 16:05:49.057',N'确认付款方式',NULL,NULL,NULL,N'USED');
INSERT INTO CRM_RECORD (CRM_RECORD_WAY,CRM_RECORD_CONTENT,CRM_CUS_ID,ADM_ID,SUP_ID,CRM_RECORD_TIME,CRM_RECORD_OB1,CRM_RECORD_OB2,CRM_RECORD_OB3,NEXT_TIME,CRM_RECORD_STATUS) VALUES
	 (N'CRM_RECORD_WAY1',西亚券商有限公司,311126,93,3,'2013-12-11 14:37:55.430',N'车欢',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY5',N'通过qq跟kendy确认付款时间，已跟kendy商量定为团组出发前14天付团款的80%',200661,456,3,'2013-12-17 17:35:57.213',N'跟kendy商量付款事宜',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',N'让找留学中心，23259222  23280324',311299,93,3,'2013-12-19 15:01:24.830',N'郗馥',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',N'惠昭',200010,93,3,'2013-12-19 15:40:20.793',N'崔胜生',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',N'以前祁国斌联系过的，他们是ISIS Education&Travel，跟天津外国语大学合作的机构，网站：http://www.isischina.com。他们做英国的接待和营地，想让我们推他们的。美国的资源他们没有，有美国团可以给我们做。',311299,93,3,'2013-12-19 17:13:33.510',N'酆妹聪',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY5',N'通过qq跟kendy联系，商量团组最终预定后的价格，最终达成一致，081，059团澳洲段地接价格均有减少',200661,456,3,'2014-01-03 14:48:24.857',N'团组价格问题',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY1',N'介绍路嘉国际游学，不需要。',311756,440,3,'2014-01-10 09:52:14.683',N'路嘉国际游学',NULL,NULL,NULL,N'USED'),
	 (N'CRM_RECORD_WAY2',N'123123',200662,19,3,'2014-07-14 19:26:54.870',N'123',NULL,NULL,NULL,N'USED');
