#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SQL Server to HSQL Converter
将 SQL Server 格式的 SQL 脚本转换为 HSQL (Hypersonic SQL) 格式
"""

import re
import sys


def convert_sqlserver_to_hsql(content):
    """转换 SQL Server 语法为 HSQL 语法"""
    
    # 1. 移除 COLLATE 子句 (HSQL 不支持)
    content = re.sub(r'\s+COLLATE\s+\S+', '', content, flags=re.IGNORECASE)
    
    # 2. 转换 IDENTITY 为 IDENTITY (HSQL 支持，但语法略有不同)
    # SQL Server: IDENTITY(1,1)
    # HSQL: GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)
    content = re.sub(
        r'IDENTITY\((\d+),(\d+)\)',
        lambda m: f'GENERATED BY DEFAULT AS IDENTITY(START WITH {m.group(1)}, INCREMENT BY {m.group(2)})',
        content,
        flags=re.IGNORECASE
    )
    
    # 3. 转换数据类型
    # nvarchar -> VARCHAR (HSQL 中 VARCHAR 支持 Unicode)
    content = re.sub(r'\bnvarchar\b', 'VARCHAR', content, flags=re.IGNORECASE)
    
    # ntext -> LONGVARCHAR (HSQL 中没有 ntext)
    content = re.sub(r'\bntext\b', 'LONGVARCHAR', content, flags=re.IGNORECASE)
    
    # datetime -> TIMESTAMP (HSQL 推荐使用 TIMESTAMP)
    content = re.sub(r'\bdatetime\b', 'TIMESTAMP', content, flags=re.IGNORECASE)
    
    # money -> DECIMAL(19,4)
    content = re.sub(r'\bmoney\b', 'DECIMAL(19,4)', content, flags=re.IGNORECASE)
    
    # numeric -> DECIMAL
    content = re.sub(r'\bnumeric\b', 'DECIMAL', content, flags=re.IGNORECASE)
    
    # float -> DOUBLE
    content = re.sub(r'\bfloat\b', 'DOUBLE', content, flags=re.IGNORECASE)
    
    # char -> CHAR
    # varchar -> VARCHAR
    
    # 4. 处理 DEFAULT 值中的 N''前缀 (Unicode 字符串)
    content = re.sub(r"DEFAULT\s+N'", "DEFAULT '", content, flags=re.IGNORECASE)
    
    # 5. 移除 EXEC sp_addextendedproperty 语句 (HSQL 使用不同的注释机制)
    content = re.sub(r'^\s*EXEC\s+.*?\.sys\.sp_addextendedproperty.*?$\n?', '', content, flags=re.IGNORECASE | re.MULTILINE)
    
    # 5.1 移除 SQL Server 特有的 CREATE INDEX 语法 (NONCLUSTERED, INCLUDE, WITH 等)
    # 完全移除这些索引创建语句
    content = re.sub(
        r'\s*CREATE\s+NONCLUSTERED\s+INDEX[^;]+;',
        '',
        content,
        flags=re.IGNORECASE
    )
    
    # 6. 转换 INSERT 语句中的 N''字符串
    # 将 N'value' 转换为'value' (HSQL 不需要 N 前缀)
    content = re.sub(r"N'([^']*)'", r"'\1'", content)
    
    # 6.1 移除 INSERT 语句中的方括号 [table_name] -> table_name
    content = re.sub(r'\[(\w+)\]', r'\1', content)
    
    # 6.2 为 CRM_COM 和 CRM_CUS 表 INSERT 语句中没有引号的中文值添加引号
    # 这个正则表达式匹配 VALUES 后面的数据行
    lines = content.split('\n')
    new_lines = []
    in_values_section = False
    
    for line in lines:
        if 'INSERT INTO' in line and 'VALUES' in line:
            in_values_section = True
        
        if in_values_section:
            import re as regex
            # 匹配没有引号的中文字符串 (至少 2 个连续汉字)
            # 但要排除 NULL、数字、已加引号的值
            def add_quotes_to_chinese(value):
                # 如果已经是 NULL、数字或带引号，不处理
                if value == 'NULL' or re.match(r'^\d+$', value) or value.startswith("'"):
                    return value
                # 如果是纯中文字符串，添加引号
                if re.match(r'^[\u4e00-\u9fa5]+$', value):
                    return f"'{value}'"
                return value
            
            # 分割并处理每个值
            parts = line.split(',')
            new_parts = []
            for part in parts:
                stripped = part.strip()
                new_parts.append(add_quotes_to_chinese(stripped))
            line = ','.join(new_parts)
        
        if ';' in line:
            in_values_section = False
            
        new_lines.append(line)
    
    content = '\n'.join(new_lines)
    
    # 7. 移除 GO 批处理分隔符
    content = re.sub(r'^\s*GO\s*$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    
    # 8. 添加 HSQL 特定的头部注释
    hsql_header = """-- HSQL Database Engine
-- Converted from SQL Server format
-- Generated by SqlServerToHsqlConverter

SET DATABASE SQL SYNTAX ORA TRUE;

"""
    
    content = hsql_header + content
    
    return content


def main():
    if len(sys.argv) < 3:
        print("用法：python3 sqlserver_to_hsql.py <input.sql> <output.sql>")
        print("例如：python3 sqlserver_to_hsql.py demo_crm_sqlserver.sql demo_crm_hsql.sql")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    print(f"正在读取文件：{input_file}")
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print("正在转换 SQL Server 语法为 HSQL 语法...")
    hsql_content = convert_sqlserver_to_hsql(content)
    
    print(f"正在写入文件：{output_file}")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(hsql_content)
    
    print("✅ 转换完成!")
    print(f"输出文件：{output_file}")


if __name__ == '__main__':
    main()
