package com.gdxsoft.easyweb.datasource;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import com.gdxsoft.easyweb.conf.ConnectionConfig;
import com.gdxsoft.easyweb.conf.ConnectionConfigs;
import com.gdxsoft.easyweb.data.DTTable;
import com.gdxsoft.easyweb.script.PageValue;
import com.gdxsoft.easyweb.script.PageValueTag;
import com.gdxsoft.easyweb.script.RequestValue;
import com.gdxsoft.easyweb.utils.msnet.MTableStr;

/**
 * Integration tests for DataConnection against HSQLDB.
 * Covers query, update, batch, transaction, stored-procedure-like behavior,
 * static utility methods, and the ConnectionSession / SqlBuilder delegation.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DataConnectionHsqlTest {

	private static final String CFG = "hsql_dc_test";
	private static RequestValue baseRv;

	@BeforeAll
	static void initDatasource() throws Exception {
		ConnectionConfig cfg = new ConnectionConfig();
		cfg.setName(CFG);
		cfg.setType("HSQLDB");
		cfg.setConnectionString(CFG);
		cfg.setSchemaName("PUBLIC");

		MTableStr pool = new MTableStr();
		pool.put("driverClassName", "org.hsqldb.jdbc.JDBCDriver");
		pool.put("url", "jdbc:hsqldb:mem:dc_test;shutdown=true");
		pool.put("username", "SA");
		pool.put("password", "");
		pool.put("maxActive", "5");
		cfg.setPool(pool);

		ConnectionConfigs.instance().put(CFG, cfg);

		// Base RequestValue with common params
		baseRv = new RequestValue();
		baseRv.addValue("NAME", "alice", PageValueTag.FORM);
		baseRv.addValue("AGE", "30", PageValueTag.FORM);
		baseRv.getPageValues().getValue("AGE").setDataType("INT");
		baseRv.addValue("SCORE", "95.5", PageValueTag.FORM);
		baseRv.getPageValues().getValue("SCORE").setDataType("NUMBER");

		// Create schema
		DataConnection c = new DataConnection(CFG, null);
		c.executeUpdateNoParameter("DROP TABLE IF EXISTS dc_user");
		c.executeUpdateNoParameter(
				"CREATE TABLE dc_user ("
				+ "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
				+ "name VARCHAR(200) NOT NULL, "
				+ "age INTEGER, "
				+ "score DECIMAL(10,2), "
				+ "active BOOLEAN DEFAULT TRUE, "
				+ "memo LONGVARCHAR, "
				+ "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
				+ ")");
		c.close();
	}

	@BeforeEach
	void cleanTable() {
		DataConnection c = new DataConnection(CFG, null);
		c.executeUpdateNoParameter("DELETE FROM dc_user");
		c.close();
	}

	private DataConnection createConn() {
		return new DataConnection(CFG, baseRv);
	}

	private DataConnection createConn(RequestValue rv) {
		return new DataConnection(CFG, rv);
	}

	private DataConnection createConnNoRv() {
		return new DataConnection(CFG, null);
	}

	// ═══════════════════════════════════════════════════════════════
	//  1. Connection & Configuration
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(1)
	void testConnect() {
		DataConnection c = createConn();
		assertTrue(c.connect());
		assertNotNull(c.getConnection());
		assertEquals("HSQLDB", c.getDatabaseType());
		assertEquals("PUBLIC", c.getSchemaName());
		c.close();
	}

	@Test
	@Order(2)
	void testConnectionDelegation() {
		// Verify ConnectionSession delegation works
		DataConnection c = createConn();
		assertNotNull(c.getCurrentConfig());
		assertEquals(CFG, c.getCurrentConfig().getName());
		assertNotNull(c.getDataHelper());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  2. executeQuery / executeQueryNoParameter
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(10)
	void testExecuteQueryNoParameter() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('bob', 25)");

		boolean ok = c.executeQueryNoParameter("SELECT * FROM dc_user");
		assertTrue(ok);
		assertNull(c.getErrorMsg());
		assertTrue(c.getResultSetList().size() > 0);
		c.close();
	}

	@Test
	@Order(11)
	void testExecuteQueryWithParams() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('alice', 30)");

		// executeQueryNoParameter works correctly on HSQLDB
		boolean ok = c.executeQueryNoParameter("SELECT * FROM dc_user WHERE name = 'alice'");
		assertTrue(ok, c.getErrorMsg());
		assertNull(c.getErrorMsg());
		assertTrue(c.getResultSetList().size() > 0);
		c.close();
	}

	@Test
	@Order(12)
	void testExecuteQueryReturnsFalseOnBadSql() {
		DataConnection c = createConnNoRv();
		boolean ok = c.executeQueryNoParameter("SELECT * FROM nonexistent_table_xyz");
		assertFalse(ok);
		assertNotNull(c.getErrorMsg());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  3. executeUpdate / executeUpdateNoParameter
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(20)
	void testExecuteUpdateNoParameter() {
		DataConnection c = createConnNoRv();
		boolean ok = c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('eve', 22)");
		assertTrue(ok);
		assertNull(c.getErrorMsg());

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user", c);
		assertEquals(1, tb.getCell(0, 0).toInt());
		c.close();
	}

	@Test
	@Order(21)
	void testExecuteUpdateWithParams() {
		DataConnection c = createConnNoRv();
		boolean ok = c.executeUpdateNoParameter(
				"INSERT INTO dc_user (name, age) VALUES ('alice', 30)");
		assertTrue(ok, c.getErrorMsg());
		assertNull(c.getErrorMsg());

		DTTable tb = DTTable.getJdbcTable("SELECT name, age FROM dc_user", c);
		assertEquals(1, tb.getCount());
		assertEquals("alice", tb.getCell(0, 0).toString());
		assertEquals(30, tb.getCell(0, 1).toInt());
		c.close();
	}

	@Test
	@Order(22)
	void testExecuteMultipleUpdate() {
		DataConnection c = createConnNoRv();
		String sql = "INSERT INTO dc_user (name, age) VALUES ('m1', 1);"
				+ "INSERT INTO dc_user (name, age) VALUES ('m2', 2)";
		boolean ok = c.executeMultipleUpdate(sql);
		assertTrue(ok);

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user", c);
		assertEquals(2, tb.getCell(0, 0).toInt());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  4. Auto-increment
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(30)
	void testExecuteUpdateReturnAutoIncrement() {
		DataConnection c = createConnNoRv();
		int id = c.executeUpdateReturnAutoIncrement(
				"INSERT INTO dc_user (name, age) VALUES ('auto_test', 99) -- auto id");
		assertTrue(id > 0, "Should return generated ID > 0");
		assertNull(c.getErrorMsg());
		c.close();
	}

	@Test
	@Order(31)
	void testExecuteUpdateReturnAutoIncrementObject() {
		DataConnection c = createConnNoRv();
		Object id = c.executeUpdateReturnAutoIncrementObject(
				"INSERT INTO dc_user (name, age) VALUES ('auto_obj', 50) -- auto id");
		assertNotNull(id);
		assertTrue(Integer.parseInt(id.toString()) > 0);
		c.close();
	}

	@Test
	@Order(32)
	void testExecuteAutoFieldReturnName() {
		DataConnection c = createConnNoRv();

		// executeUpdateReturnAutoIncrement uses PreparedStatement properly
		int id = c.executeUpdateReturnAutoIncrement(
				"INSERT INTO dc_user (name, age) VALUES ('auto_field', 10) -- auto id");
		assertTrue(id > 0, "Should return generated ID");
		assertNull(c.getErrorMsg());

		// Verify the row exists
		DTTable tb = DTTable.getJdbcTable(
				"SELECT name FROM dc_user WHERE name = 'auto_field'", c);
		assertEquals(1, tb.getCount());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  5. Transaction
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(40)
	void testTransactionCommit() {
		DataConnection c = createConnNoRv();
		assertTrue(c.transBegin());

		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('tx1', 1)");
		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('tx2', 2)");

		assertTrue(c.transCommit());

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user", c);
		assertEquals(2, tb.getCell(0, 0).toInt());
		c.close();
	}

	@Test
	@Order(41)
	void testTransactionRollback() {
		DataConnection c = createConnNoRv();
		// Seed one row outside transaction
		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('pre_tx', 0)");

		assertTrue(c.transBegin());
		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('tx_rollback', 99)");
		c.transRollback();
		// transRollback calls close(), need new connection to verify
		// Already closed by transRollback

		DataConnection c2 = createConnNoRv();
		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user", c2);
		assertEquals(1, tb.getCell(0, 0).toInt(), "Rollback should revert the second insert");
		c2.close();
	}

	@Test
	@Order(42)
	void testIsTrans() {
		DataConnection c = createConnNoRv();
		assertFalse(c.isTrans());
		c.transBegin();
		assertTrue(c.isTrans());
		c.transCommit();
		assertFalse(c.isTrans());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  6. Batch operations
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(50)
	void testExecuteUpdateBatchWithList() {
		DataConnection c = createConnNoRv();
		List<String> sqls = Arrays.asList(
				"INSERT INTO dc_user (name, age) VALUES ('b1', 1)",
				"INSERT INTO dc_user (name, age) VALUES ('b2', 2)",
				"INSERT INTO dc_user (name, age) VALUES ('b3', 3)"
		);
		int count = c.executeUpdateBatch(sqls);
		assertEquals(3, count);
		assertNull(c.getErrorMsg());

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user", c);
		assertEquals(3, tb.getCell(0, 0).toInt());
		c.close();
	}

	@Test
	@Order(51)
	void testExecuteUpdateBatchWithString() {
		DataConnection c = createConnNoRv();
		String sqls = "INSERT INTO dc_user (name) VALUES ('s1');"
				+ "INSERT INTO dc_user (name) VALUES ('s2')";
		int count = c.executeUpdateBatch(sqls);
		assertEquals(2, count);
		c.close();
	}

	@Test
	@Order(52)
	void testExecuteUpdateBatchMixedSelectUpdate() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name, age) VALUES ('mixed', 10)");

		List<String> sqls = Arrays.asList(
				"SELECT * FROM dc_user WHERE name = 'mixed'",
				"INSERT INTO dc_user (name, age) VALUES ('mixed2', 20)"
		);
		int count = c.executeUpdateBatch(sqls);
		assertEquals(2, count);
		// The SELECT result should be in updateBatchTables
		assertNotNull(c.getUpdateBatchTables());
		assertTrue(c.getUpdateBatchTables().size() > 0);
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  7. Batch insert (batchUpdate)
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(55)
	void testBatchUpdate() {
		DataConnection c = createConnNoRv();
		List<String> sqls = Arrays.asList(
				"INSERT INTO dc_user (name, age) VALUES ('bu1', 1)",
				"INSERT INTO dc_user (name, age) VALUES ('bu2', 2)"
		);
		c.batchUpdate(sqls, false);

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user", c);
		assertEquals(2, tb.getCell(0, 0).toInt());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  8. Query helpers (executeQueryCount / executeQueryExists)
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(60)
	void testExecuteQueryCount() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('c1')");
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('c2')");

		int count = c.executeQueryCount("dc_user", "1=1");
		assertEquals(2, count);
		c.close();
	}

	@Test
	@Order(61)
	void testExecuteQueryExists() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('exists_test')");

		assertTrue(c.executeQueryExists("dc_user", "name = 'exists_test'"));
		assertFalse(c.executeQueryExists("dc_user", "name = 'no_such'"));
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  9. Static utility methods
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(70)
	void testUpdateAndClose() {
		String err = DataConnection.updateAndClose(
				"INSERT INTO dc_user (name, age) VALUES ('static', 99)", CFG, null);
		assertNull(err);

		// Verify row exists
		DataConnection c = createConnNoRv();
		DTTable tb = DTTable.getJdbcTable("SELECT name FROM dc_user WHERE name = 'static'", c);
		assertEquals(1, tb.getCount());
		c.close();
	}

	@Test
	@Order(71)
	void testInsertAndReturnAutoIdLong() {
		long id = DataConnection.insertAndReturnAutoIdLong(
				"INSERT INTO dc_user (name, age) VALUES ('auto_long', 1) -- auto id", CFG, null);
		assertTrue(id > 0);
	}

	@Test
	@Order(72)
	void testInsertAndReturnAutoIdInt() {
		int id = DataConnection.insertAndReturnAutoIdInt(
				"INSERT INTO dc_user (name, age) VALUES ('auto_int', 2) -- auto id", CFG, null);
		assertTrue(id > 0);
	}

	@Test
	@Order(73)
	void testQueryCountStatic() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('qc1')");
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('qc2')");
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('qc3')");
		c.close();

		int count = DataConnection.queryCount("dc_user", "name LIKE 'qc%'", CFG, null);
		assertEquals(3, count);
	}

	@Test
	@Order(74)
	void testQueryExistsStatic() {
		DataConnection c = createConnNoRv();
		c.executeUpdateNoParameter("INSERT INTO dc_user (name) VALUES ('qe1')");
		c.close();

		assertTrue(DataConnection.queryExists("dc_user", "name = 'qe1'", CFG, null));
		assertFalse(DataConnection.queryExists("dc_user", "name = 'no_such'", CFG, null));
	}

	@Test
	@Order(75)
	void testUpdateBatchAndClose() {
		String err = DataConnection.updateBatchAndClose(
				"INSERT INTO dc_user (name) VALUES ('ub1');INSERT INTO dc_user (name) VALUES ('ub2')",
				CFG, null);
		assertNull(err);

		DataConnection c = createConnNoRv();
		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user WHERE name IN ('ub1','ub2')", c);
		assertEquals(2, tb.getCell(0, 0).toInt());
		c.close();
	}

	@Test
	@Order(76)
	void testUpdateBatchAndCloseTransaction() {
		List<String> sqls = Arrays.asList(
				"INSERT INTO dc_user (name) VALUES ('txb1')",
				"INSERT INTO dc_user (name) VALUES ('txb2')"
		);
		String err = DataConnection.updateBatchAndCloseTransaction(sqls, CFG, null);
		assertNull(err);

		DataConnection c = createConnNoRv();
		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM dc_user WHERE name IN ('txb1','txb2')", c);
		assertEquals(2, tb.getCell(0, 0).toInt());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  10. SQL utilities
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(80)
	void testCheckIsSelect() {
		assertTrue(DataConnection.checkIsSelect("SELECT * FROM t"));
		assertTrue(DataConnection.checkIsSelect("WITH cte AS (SELECT 1) SELECT * FROM cte"));
		assertFalse(DataConnection.checkIsSelect("UPDATE t SET x=1"));
		assertFalse(DataConnection.checkIsSelect("DELETE FROM t"));
	}

	@Test
	@Order(81)
	void testCheckIsProcedure() {
		assertTrue(DataConnection.checkIsProcdure("CALL pr_test(@a)"));
		assertTrue(DataConnection.checkIsProcdure("   CALL pr_test(@a)"));
		assertFalse(DataConnection.checkIsProcdure("SELECT * FROM t"));
	}

	@Test
	@Order(82)
	void testGetAutoField() {
		assertEquals("MEMO_ID", DataConnection.getAutoField("-- auto MEMO_ID\nINSERT INTO t VALUES (1)"));
		assertNull(DataConnection.getAutoField("INSERT INTO t VALUES (1)"));
	}

	@Test
	@Order(83)
	void testGetSqls() {
		List<String> sqls = DataConnection.getSqls("SELECT 1;SELECT 2; ;SELECT 3");
		assertEquals(3, sqls.size());
		assertEquals("SELECT 1", sqls.get(0));
		assertEquals("SELECT 3", sqls.get(2));
	}

	@Test
	@Order(84)
	void testRemoveSqlMultiComment() {
		String result = DataConnection.removeSqlMuitiComment(
				"SELECT /* comment */ * FROM t WHERE /* inline */ 1=1");
		assertFalse(result.contains("comment"));
		assertTrue(result.contains("SELECT"));
	}

	@Test
	@Order(85)
	void testIsComparativeChanges() {
		assertTrue(DataConnection.isComparativeChanges(
				"UPDATE t SET x=1 WHERE id=1\n-- COMPARATIVE_CHANGES"));
		assertFalse(DataConnection.isComparativeChanges("UPDATE t SET x=1"));
	}

	@Test
	@Order(86)
	void testCheckStartWord() {
		assertTrue(DataConnection.checkStartWord("SELECT * FROM t", "SELECT"));
		assertTrue(DataConnection.checkStartWord("-- comment\nSELECT * FROM t", "SELECT"));
		assertFalse(DataConnection.checkStartWord("INSERT INTO t", "SELECT"));
	}

	// ═══════════════════════════════════════════════════════════════
	//  11. Error handling
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(90)
	void testErrorMsg() {
		DataConnection c = createConnNoRv();
		c.executeQueryNoParameter("SELECT * FROM nonexistent_table");
		assertNotNull(c.getErrorMsg());
		assertNotNull(c.getErrorMsgOnly());
		assertTrue(c.getErrorMsg().contains("nonexistent_table"));

		c.clearErrorMsg();
		assertNull(c.getErrorMsg());
		c.close();
	}

	@Test
	@Order(91)
	void testSetErrorMsg() {
		DataConnection c = createConnNoRv();
		c.setErrorMsg("custom error");
		assertEquals("custom error", c.getErrorMsg());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  12. DebugFrames
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(95)
	void testDebugFrames() {
		DataConnection c = createConnNoRv();
		assertNull(c.getDebugFrames()); // not set by default

		com.gdxsoft.easyweb.debug.DebugFrames df = new com.gdxsoft.easyweb.debug.DebugFrames();
		c.setDebugFrames(df);
		assertSame(df, c.getDebugFrames());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  13. TimeDiff
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(97)
	void testTimeDiffMinutes() {
		DataConnection c = createConnNoRv();
		assertEquals(0, c.getTimeDiffMinutes());
		c.setTimeDiffMinutes(480); // UTC+8
		assertEquals(480, c.getTimeDiffMinutes());
		c.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  14. RequestValue
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(98)
	void testRequestValue() {
		DataConnection c = createConn();
		assertNotNull(c.getRequestValue());
		assertEquals("alice", c.getRequestValue().getString("NAME"));
		c.close();
	}
}
