package com.gdxsoft.easyweb.datasource;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.PreparedStatement;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import com.gdxsoft.easyweb.conf.ConnectionConfig;
import com.gdxsoft.easyweb.conf.ConnectionConfigs;
import com.gdxsoft.easyweb.data.DTTable;
import com.gdxsoft.easyweb.script.PageValue;
import com.gdxsoft.easyweb.script.PageValueTag;
import com.gdxsoft.easyweb.script.RequestValue;
import com.gdxsoft.easyweb.utils.msnet.MListStr;
import com.gdxsoft.easyweb.utils.msnet.MTableStr;

/**
 * Tests for SqlBuilder — SQL text building, parameter binding, and type
 * conversion. Uses HSQLDB in-memory database.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class SqlBuilderTest {

	private static final String CFG = "hsql_sqlbuilder_test";
	private static DataConnection conn;
	private static RequestValue rv;

	@BeforeAll
	static void setUp() throws Exception {
		ConnectionConfig cfg = new ConnectionConfig();
		cfg.setName(CFG);
		cfg.setType("HSQLDB");
		cfg.setConnectionString(CFG);
		cfg.setSchemaName("PUBLIC");

		MTableStr pool = new MTableStr();
		pool.put("driverClassName", "org.hsqldb.jdbc.JDBCDriver");
		pool.put("url", "jdbc:hsqldb:mem:sqlbuilder_test;shutdown=true");
		pool.put("username", "SA");
		pool.put("password", "");
		pool.put("maxActive", "2");
		cfg.setPool(pool);

		ConnectionConfigs.instance().put(CFG, cfg);

		rv = new RequestValue();
		rv.addValue("NAME", "test_user", PageValueTag.FORM);
		rv.addValue("AGE", "25", PageValueTag.FORM);
		rv.addValue("SCORE", "98.5", PageValueTag.FORM);
		rv.addValue("IDS_SPLIT", "1,2,3", PageValueTag.FORM);
		rv.getPageValues().getValue("AGE").setDataType("INT");
		rv.getPageValues().getValue("SCORE").setDataType("NUMBER");

		conn = new DataConnection(CFG, rv);
		conn.executeUpdateNoParameter(
				"CREATE TABLE test_user ("
				+ "id INTEGER GENERATED BY DEFAULT AS IDENTITY, "
				+ "name VARCHAR(200) NOT NULL, "
				+ "age INTEGER, "
				+ "score DECIMAL(10,2), "
				+ "active BOOLEAN DEFAULT TRUE, "
				+ "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
				+ ")");
	}

	@AfterAll
	static void tearDown() {
		if (conn != null) conn.close();
		DataHelper.closeDataSource(CFG);
	}

	// ═══════════════════════════════════════════════════════════════
	//  rebuildSql tests
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(1)
	void testRebuildSqlNullSafety() throws Exception {
		RequestValue emptyRv = new RequestValue();
		DataConnection c = new DataConnection(CFG, emptyRv);
		assertNull(c.rebuildSql(null));
		c.close();
	}

	@Test
	@Order(2)
	void testRebuildSqlWithParam() throws Exception {
		String result = conn.rebuildSql("SELECT * FROM test_user WHERE name = @NAME");
		// rebuildSql preserves @paramName for later inline/parameter binding
		assertTrue(result.contains("@NAME"));
	}

	@Test
	@Order(3)
	void testRebuildSqlSplitParam() throws Exception {
		String result = conn.rebuildSql("SELECT * FROM test_user WHERE id IN (@IDS_SPLIT)");
		assertTrue(result.contains("'1'"));
		assertTrue(result.contains("'2'"));
		assertTrue(result.contains("'3'"));
	}

	@Test
	@Order(4)
	void testRebuildSqlNullParam() throws Exception {
		RequestValue rv2 = new RequestValue();
		DataConnection c2 = new DataConnection(CFG, rv2);
		String result = c2.rebuildSql("SELECT * FROM test_user WHERE age = @MISSING");
		assertTrue(result.toLowerCase().contains("null"));
		c2.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  replaceSqlParameters
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(10)
	void testReplaceSqlParameters() {
		String result = conn.replaceSqlParameters("SELECT * FROM t WHERE a = @NAME AND b = @AGE");
		assertEquals("SELECT * FROM t WHERE a = ? AND b = ?", result);
	}

	@Test
	@Order(11)
	void testReplaceSqlParametersAtPreservation() {
		String result = conn.replaceSqlParameters("SELECT '{@}' AS keep_at");
		assertTrue(result.contains("@"));
	}

	// ═══════════════════════════════════════════════════════════════
	//  skipReplaceParameter
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(20)
	void testSkipReplaceRownum() {
		assertTrue(conn.skipReplaceParameter("rownum"));
		assertTrue(conn.skipReplaceParameter("ROWNUM"));
		assertFalse(conn.skipReplaceParameter("my_rownum"));
		assertFalse(conn.skipReplaceParameter(null));
	}

	// ═══════════════════════════════════════════════════════════════
	//  getParameterByEndWithType
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(30)
	void testGetParameterByEndWithType() {
		PageValue pv;
		pv = conn.getParameterByEndWithType("user_id.int");
		assertEquals("int", pv.getDataType());
		pv = conn.getParameterByEndWithType("user_id.long");
		assertEquals("bigint", pv.getDataType());
		pv = conn.getParameterByEndWithType("user_id.bigint");
		assertEquals("bigint", pv.getDataType());
		pv = conn.getParameterByEndWithType("start.date");
		assertEquals("date", pv.getDataType());
		pv = conn.getParameterByEndWithType("price.number");
		assertEquals("number", pv.getDataType());
		pv = conn.getParameterByEndWithType("data.binary");
		assertEquals("binary", pv.getDataType());
	}

	// ═══════════════════════════════════════════════════════════════
	//  sqlParameterStringExp
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(40)
	void testSqlParameterStringExp() {
		assertEquals("NULL", conn.sqlParameterStringExp(null));
		assertEquals("''", conn.sqlParameterStringExp(""));
		assertEquals("'hello'", conn.sqlParameterStringExp("hello"));
		assertEquals("'it''s'", conn.sqlParameterStringExp("it's"));
	}

	// ═══════════════════════════════════════════════════════════════
	//  sqlFieldOrTableExp
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(45)
	void testSqlFieldOrTableExp() {
		assertEquals("my_table", conn.sqlFieldOrTableExp("my_table"));
	}

	// ═══════════════════════════════════════════════════════════════
	//  createSqlByEwaTest
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(50)
	void testCreateSqlByEwaTestWithCondition() {
		RequestValue rv2 = new RequestValue();
		rv2.addValue("TAG", "CAR", PageValueTag.FORM);
		DataConnection c2 = new DataConnection(CFG, rv2);

		String sql = "SELECT * FROM test_user WHERE 1=1\n"
				+ "-- ewa_test @TAG is not null\n"
				+ "  AND name = @TAG\n"
				+ "-- ewa_test\n"
				+ "ORDER BY id";
		String result = c2.createSqlByEwaTest(sql);
		assertTrue(result.contains("AND name"), "Conditional SQL should be included");
		c2.close();
	}

	@Test
	@Order(51)
	void testCreateSqlByEwaTestWithoutCondition() {
		RequestValue rv2 = new RequestValue();
		DataConnection c2 = new DataConnection(CFG, rv2);

		String sql = "SELECT * FROM test_user WHERE 1=1\n"
				+ "-- ewa_test @TAG is not null\n"
				+ "  AND name = @TAG\n"
				+ "-- ewa_test\n"
				+ "ORDER BY id";
		String result = c2.createSqlByEwaTest(sql);
		assertFalse(result.contains("AND name"), "Conditional SQL excluded when TAG is null");
		c2.close();
	}

	// ═══════════════════════════════════════════════════════════════
	//  replaceSqlCommentAtSymbol
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(55)
	void testReplaceSqlCommentAtSymbol() {
		String result = conn.replaceSqlCommentAtSymbol(
				"SELECT * FROM t\n-- comment with @param\nWHERE x = @param");
		assertTrue(result.contains("&#64;param"), "@ in comment should be escaped");
		assertTrue(result.contains("WHERE x = @param"), "@ in SQL should NOT be escaped");
	}

	// ═══════════════════════════════════════════════════════════════
	//  getDateTimePara
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(60)
	void testGetDateTimeParaNull() {
		assertNull(conn.getDateTimePara((String) null));
		assertNull(conn.getDateTimePara(""));
	}

	@Test
	@Order(61)
	void testGetDateTimeParaWithString() {
		String result = conn.getDateTimePara("2024-01-15 10:30:00");
		assertNotNull(result);
		assertTrue(result.startsWith("'"));
		assertTrue(result.endsWith("'"));
	}

	// ═══════════════════════════════════════════════════════════════
	//  addStatementParameter integration
	// ═══════════════════════════════════════════════════════════════

	@Test
	@Order(70)
	void testAddStatementParameterString() throws Exception {
		conn.executeUpdateNoParameter("DELETE FROM test_user");

		RequestValue rv2 = new RequestValue();
		rv2.addValue("N", "parameter_test", PageValueTag.FORM);
		DataConnection c2 = new DataConnection(CFG, rv2);

		String sql = c2.rebuildSql("INSERT INTO test_user (name, age) VALUES (@N, 1)");
			sql = c2.replaceSqlParameters(sql); // convert @N to ?
		PreparedStatement pst = conn.getDataHelper().getPreparedStatement(sql);
		MListStr params = new MListStr();
		params.add("N");
		c2.addSqlParameter(params, pst);
		pst.executeUpdate();
		conn.getDataHelper().getConnection().commit();
		pst.close();

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM test_user WHERE name = 'parameter_test'", conn);
		assertEquals(1, tb.getCell(0, 0).toInt());
		c2.close();
	}

	@Test
	@Order(71)
	void testAddStatementParameterNullValue() throws Exception {
		conn.executeUpdateNoParameter("DELETE FROM test_user");

		RequestValue rv2 = new RequestValue();
		rv2.addValue("N", "null_test", PageValueTag.FORM);
		rv2.addValue("A", (String) null, PageValueTag.FORM);
		rv2.getPageValues().getValue("A").setDataType("INT");
		DataConnection c2 = new DataConnection(CFG, rv2);

		// Use explicit ? placeholders (rebuildSql replaces null params with "null" literal)
		String sql = "INSERT INTO test_user (name, age) VALUES (?, ?)";
		PreparedStatement pst = conn.getDataHelper().getPreparedStatement(sql);
		MListStr params = new MListStr();
		params.add("N");
		params.add("A");
		c2.addSqlParameter(params, pst);
		pst.executeUpdate();
		conn.getDataHelper().getConnection().commit();
		pst.close();

		DTTable tb = DTTable.getJdbcTable("SELECT age FROM test_user WHERE name = 'null_test'", conn);
		assertEquals(1, tb.getCount());
		assertTrue(tb.getCell(0, 0).isNull());
		c2.close();
	}

	@Test
	@Order(72)
	void testAddStatementParameterInt() throws Exception {
		conn.executeUpdateNoParameter("DELETE FROM test_user");

		RequestValue rv2 = new RequestValue();
		rv2.addValue("N", "int_test", PageValueTag.FORM);
		rv2.addValue("A", "42", PageValueTag.FORM);
		rv2.getPageValues().getValue("A").setDataType("INT");
		DataConnection c2 = new DataConnection(CFG, rv2);

		String sql = c2.rebuildSql("INSERT INTO test_user (name, age) VALUES (@N, @A)");
			sql = c2.replaceSqlParameters(sql); // convert @N,@A to ?
		PreparedStatement pst = conn.getDataHelper().getPreparedStatement(sql);
		MListStr params = new MListStr();
		params.add("N");
		params.add("A");
		c2.addSqlParameter(params, pst);
		pst.executeUpdate();
		conn.getDataHelper().getConnection().commit();
		pst.close();

		DTTable tb = DTTable.getJdbcTable("SELECT age FROM test_user WHERE name = 'int_test'", conn);
		assertEquals(42, tb.getCell(0, 0).toInt());
		c2.close();
	}

	@Test
	@Order(73)
	void testAddStatementParameterRequestValueNull() throws Exception {
		// Create connection with NO RequestValue
		DataConnection c2 = new DataConnection(CFG, null);

		// Use a table without NOT NULL constraint for this test
		c2.executeUpdateNoParameter("CREATE TABLE IF NOT EXISTS test_nullable (val VARCHAR(100))");
		c2.executeUpdateNoParameter("DELETE FROM test_nullable");

		String sql = "INSERT INTO test_nullable (val) VALUES (?)";
		PreparedStatement pst = c2.getDataHelper().getPreparedStatement(sql);
		// When RequestValue is null, setObject(null) is called
		c2.addStatementParameter(pst, "ANY", 1);
		pst.executeUpdate();
		c2.getDataHelper().getConnection().commit();
		pst.close();

		DTTable tb = DTTable.getJdbcTable("SELECT COUNT(*) FROM test_nullable", c2);
		assertTrue(tb.getCell(0, 0).toInt() > 0);
		c2.close();
	}
}
